### ISSUE TITLE
Question for release

### ISSUE THREAD

**Issue by jog2Sa** [rt219/LatentGuard#1]
@rt219 Dear Liu, could u please tell me when the data and code will be released?

**Comment by fabvio** [comment]
Hi, thanks for your interest.
The code and data will be released when the paper is accepted. We hope this is going to be in a couple of weeks. Thank you for your patience and understanding.

**Comment by jog2Sa** [comment]
> Hi, thanks for your interest. The code and data will be released when the paper is accepted. We hope this is going to be in a couple of weeks. Thank you for your patience and understanding.

I greatly appreciate your reply.But sorry for my absurdity, I have another question : what about the CoPro dataset? Would it be possible to release CoPro in advance?

**Comment by fabvio** [comment]
We can discuss this. Please send me an email in which you describe the intended usage of the dataset. Thanks!
